namespace EnterpriseMediator.Contracts.Common;

/// <summary>
/// Marker interface ensuring all integration events have standard metadata
/// for idempotency, distributed tracing, and temporal ordering.
/// </summary>
public interface IIntegrationEvent
{
    /// <summary>
    /// Unique identifier for idempotent processing. Generated by the publisher.
    /// </summary>
    Guid EventId { get; init; }

    /// <summary>
    /// Correlation identifier for distributed tracing across services.
    /// </summary>
    Guid CorrelationId { get; init; }

    /// <summary>
    /// UTC timestamp of when the event was created.
    /// </summary>
    DateTimeOffset CreatedAt { get; init; }
}
