using System;
using System.Collections.Generic;
using EnterpriseMediator.Domain.Common;
using EnterpriseMediator.Domain.Common.Exceptions;
using EnterpriseMediator.Domain.Shared.ValueObjects;

namespace EnterpriseMediator.Domain.ProjectManagement.Aggregates;

/// <summary>
/// Represents the sanitized, structured requirements for a project, extracted from an SOW.
/// This acts as the "public" face of the project requirements for vendor matching.
/// </summary>
public class ProjectBrief : Entity<Guid>
{
    public ProjectId ProjectId { get; private set; }
    public string ScopeSummary { get; private set; }
    public List<string> RequiredSkills { get; private set; }
    public List<string> Deliverables { get; private set; }
    public string TimelineDescription { get; private set; }
    
    // The vector embedding of this brief used for semantic search (REQ-FUNC-014)
    public EmbeddingVector? Embedding { get; private set; }
    
    public bool IsApproved { get; private set; }
    public DateTimeOffset? ApprovedAt { get; private set; }

    // EF Core
    protected ProjectBrief() 
    {
        RequiredSkills = new List<string>();
        Deliverables = new List<string>();
        ScopeSummary = string.Empty;
        TimelineDescription = string.Empty;
    }

    public ProjectBrief(ProjectId projectId, string scopeSummary, List<string> requiredSkills, List<string> deliverables, string timelineDescription)
    {
        if (string.IsNullOrWhiteSpace(scopeSummary))
            throw new BusinessRuleValidationException("Scope summary is required for a Project Brief.");

        Id = Guid.NewGuid();
        ProjectId = projectId;
        ScopeSummary = scopeSummary;
        RequiredSkills = requiredSkills ?? new List<string>();
        Deliverables = deliverables ?? new List<string>();
        TimelineDescription = timelineDescription;
        IsApproved = false;
    }

    /// <summary>
    /// Updates the brief details. Only allowed if the brief is not yet approved.
    /// </summary>
    public void UpdateDetails(string scopeSummary, List<string> requiredSkills, List<string> deliverables, string timelineDescription)
    {
        if (IsApproved)
            throw new BusinessRuleValidationException("Cannot update Project Brief details after it has been approved.");

        if (string.IsNullOrWhiteSpace(scopeSummary))
            throw new BusinessRuleValidationException("Scope summary cannot be empty.");

        ScopeSummary = scopeSummary;
        RequiredSkills = requiredSkills ?? new List<string>();
        Deliverables = deliverables ?? new List<string>();
        TimelineDescription = timelineDescription;
        
        // Reset embedding if content changes significantly? 
        // In this design, we assume the embedding is regenerated by a domain service or external worker
        // and set via SetEmbedding.
        Embedding = null; 
    }

    /// <summary>
    /// Sets the vector embedding generated from the brief's content.
    /// </summary>
    public void SetEmbedding(EmbeddingVector embedding)
    {
        Embedding = embedding ?? throw new ArgumentNullException(nameof(embedding));
    }

    /// <summary>
    /// Approves the brief, making it immutable and ready for distribution (US-036).
    /// </summary>
    public void Approve()
    {
        if (IsApproved) return;

        if (string.IsNullOrWhiteSpace(ScopeSummary))
            throw new BusinessRuleValidationException("Cannot approve a brief with no scope summary.");

        if (RequiredSkills.Count == 0)
            throw new BusinessRuleValidationException("Cannot approve a brief with no required skills.");

        IsApproved = true;
        ApprovedAt = DateTimeOffset.UtcNow;
    }
}